gerador/urls.py
from django.urls import path
from .views import upload_pdf, count_pages_view, pdf_page

urlpatterns = [
    path('upload_pdf', upload_pdf, name='upload_pdf'),
    path('count_pages/', count_pages_view, name='cou nt_pages_view'),
    path('', pdf_page, name='pdf_page'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerador.urls')),
]
    

gerador/models.py
from django.db import models

class UploadedPDF(models.Model):
    pdf_file = models.FileField(upload_to='media/')

gerador/forms.py
from django import forms
from .models import UploadedPDF

class UploadPDFForm(forms.ModelForm):
    class Meta:
        model = UploadedPDF
        fields = ['pdf_file']

gerador/views.py
# No seu arquivo views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .forms import UploadPDFForm
from PyPDF2 import PdfReader

def pdf_page(request):
    return render(request, "pdf.html")


def count_pages(pdf_paths):
    total_pages = 0

    for pdf_path in pdf_paths:
        with open(pdf_path, 'rb') as pdf_file:
            pdf_reader = PdfReader(pdf_file)
            total_pages += len(pdf_reader.pages)

    return total_pages

def upload_pdf(request):
    if request.method == 'POST':
        form = UploadPDFForm(request.POST, request.FILES)
        if form.is_valid():
            pdf_instances = form.save(commit=False)
            pdf_paths = [pdf_instance.pdf_file.path for pdf_instance in pdf_instances]
            total_pages = count_pages(pdf_paths)
            return render(request, 'result.html', {'total_pages': total_pages})
    else:
        form = UploadPDFForm()
    return render(request, 'upload.html', {'form': form})

@csrf_exempt
def count_pages_view(request):
    if request.method == 'POST':
        files = request.FILES.getlist('pdf_files')
        pdf_paths = [handle_uploaded_file(f) for f in files]
        total_pages = count_pages(pdf_paths)
        return JsonResponse({'total_pages': total_pages})

def handle_uploaded_file(file):
    # Método para salvar os arquivos temporários e retornar o caminho
    # Certifique-se de tratar isso de maneira adequada no seu projeto real
    # O exemplo abaixo salva temporariamente os arquivos no diretório de mídia temporária do Django
    import os
    from django.conf import settings

    temp_dir = os.path.join(settings.MEDIA_ROOT, 'temp')
    os.makedirs(temp_dir, exist_ok=True)

    file_path = os.path.join(temp_dir, file.name)

    with open(file_path, 'wb') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

    return file_path

gerador/templates/pdf.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/style21.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'js/SplitText3.min.js' %}"></script>
    <script src="{% static 'js/gsap.min.js' %}"></script>
   
    


   
   
</head>
<body>
{% block content %}

    <div id="green-filter"></div>
<div id="top-gradient" class="gradient"></div>
<div id="bottom-gradient" class="gradient"></div>
<div id="logo-wrapper">
  <div id="logo">
    <div id="logo-border" class="absolute-centered"></div>
    <div id="logo-border-inner" class="absolute-centered"></div>
    <div id="logo-text">
      <div id="hulu-text" class="zen-dots-font">PDF</div>
      <div id="originals-text" class="jakarta-sans-font">Calculo</div>
      {% endblock content %}
    </div>
  </div>
</div>

<a href="{% url 'upload_pdf' %}" id="restart-button" class="bubbly-button">Clique aqui</a>




<script src="{% static 'js/renderv2.js' %}"></script>
</body>
</html>

gerador/templates/result.html
<!DOCTYPE html>
<html>
<head>
    <title>Result</title>
</head>
<body>
    <h2>Result</h2>
    <p>Total Pages: {{ total_pages }}</p>
</body>
</html>

gerador/templates/upload.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Upload PDF</title>
    <link href="{% static 'css/page2/button.css' %}" rel="stylesheet">
    <script src="{% static 'js/page2/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/page2/sbutton.js' %}"></script>


   

   


  
</head>
<body>
    <!-- Hamburger to Close -->
<div class="container">
	<div class="closeburger">
		<div class="middleburger"></div>
	</div>
</div>


<div class="upload-pdf">
    <h2 class="center">Upload PDF</h2>
    <div class="file-upload">
      <label for="id_pdf_file">Selecione os arquivos</label>
      <input type="file" name="pdf_file" id="id_pdf_file" multiple>
    </div>
   
    <button type="button" onclick="countPages()">Contar Páginas</button>
  </div>
  
    <script>
        function countPages() {
            var files = document.getElementById('id_pdf_file').files;
            var formData = new FormData();

            for (var i = 0; i < files.length; i++) {
                formData.append('pdf_files', files[i]);
            }

            $.ajax({
                url: '/count_pages/',  // Substitua pelo URL da sua view Django
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function(response) {
                    alert('Número total de páginas: ' + response.total_pages);
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    
    </script>
  

    
    


</body>
</html>